name: Build and Publish

on:
  workflow_dispatch:

jobs:
  build:

    env:
      PROJECT: StereoKit.Templates.csproj
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore $PROJECT
    - name: Pack
      run: dotnet pack --configuration Release $PROJECT
